# Generated by Django 5.0.3 on 2024-04-03 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='receita',
            name='grau_de_dificuldade',
            field=models.CharField(choices=[('facil', 'facil'), ('medio', 'medio'), ('dificil', 'dificil')], max_length=10),
        ),
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ReceitaApp.categoria'),
        ),
    ]
